[build]
publish = "public"
command = "npm run pre-build && hugo --gc --minify"
base = "assets/.netlify/"
ignore = "git diff --quiet HEAD^ HEAD -- ../"

[context.production.environment]
HUGO_VERSION = "0.59.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = 'npm run pre-build && hugo --gc --minify -b $DEPLOY_PRIME_URL --enableGitInfo'

[context.deploy-preview.environment]
HUGO_VERSION = "0.59.1"

[context.branch-deploy]
command = 'npm run pre-build && hugo --gc --minify -b $DEPLOY_PRIME_URL --enableGitInfo'

[context.branch-deploy.environment]
HUGO_VERSION = "0.59.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
